export const EMPLOYEE_ARRAY = [
  "PI",
  "offl",
  "app",
  "f23",
  "lrc1031a",
  "jd",
  "rc",
  "tc",
  "binf",
  "fw4",
  "aps",
  "fw9",
  "i9",
  "onsfov",
  "st",
  "etracking",
  "ic",
  "asam",
  "fprt",
  "et",
  "tr",
  "staffsch",
  "timesheet",
  "perf",
];

export const INTAKE_ARRAY = ["iass", "nass", "tp", "fs", "sp", "ri"];

export const CONTACT_ARRAY = [
  "pn",
  "discharge",
  "sn",
  "asamc",
  "dp",
  "ron",
  "bhpn",
  "spn",
  "tn",
  "aschedule",
  "cn",
  "ml",
  "ari",
  "rt",
  "mppr",
  "ft",
  "dtf",
];

export const DOCUMENT_ARRAY = ["cf", "df", "uf"];

export const MEDICAL_ARRAY = [
  "rv",
  "em",
  "mars",
  "mr",
  "ms",
  "rmt",
  "mc",
  "icm",
  "prn",
];

export const CALENDAR_ARRAY = ["ba", "va", "ma", "ahis"];
export const CLINICAL_ARRAY = ["co"];
export const INCIDENT_ARRAY = ["inr"];
export const REASSESSMENT_ARRAY = ["reassessment"];

export const EMPLOYEE_TYPE_OPTION = [
  { _id: 1, label: "Regular", value: "regular" },
  { _id: 2, label: "Read Only", value: "restricted" },
  { _id: 3, label: "Adminstrator", value: "adminstrator" },
];

export const PATIENT_TYPE_OPTION = [
  { _id: 1, label: "Regular", value: "regular" },
  { _id: 2, label: "Read Only", value: "restricted" },
];

export const PERMISSION_CATEGORY_ARRAYS = {
  employeeInfo: EMPLOYEE_ARRAY,
  intake: INTAKE_ARRAY,
  contact: CONTACT_ARRAY,
  document: DOCUMENT_ARRAY,
  medical: MEDICAL_ARRAY,
  calendar: CALENDAR_ARRAY,
  clinical: CLINICAL_ARRAY,
  incident: INCIDENT_ARRAY,
  reassessmentCategory: REASSESSMENT_ARRAY,
};

export const DEFAULT_CHECKBOX_VALUES = {
  editEmployee: false,
  deleteEmployee: false,
  editIntake: false,
  deleteIntake: false,
  editContact: false,
  deleteContact: false,
  editDocument: false,
  deleteDocument: false,
  editMedical: false,
  deleteMedical: false,
  editCalendar: false,
  deleteCalendar: false,
  editClinical: false,
  deleteClinical: false,
  editIncident: false,
  deleteIncident: false,
  editReassessment: false,
  co: false,
  inr: false,
  PI: false,
  offl: false,
  app: false,
  f23: false,
  lrc1031a: false,
  jd: false,
  rc: false,
  fw4: false,
  aps: false,
  fw9: false,
  i9: false,
  onsfov: false,
  st: false,
  ic: false,
  asam: false,
  fprt: false,
  et: false,
  tr: false,
  staffsch: false,
  timesheet: false,
  perf: false,
  etracking: false,
  tc: false,
  binf: false,
  pn: false,
  discharge: false,
  bhpn: false,
  dp: false,
  ron: false,
  asamc: false,
  sn: false,
  spn: false,
  tn: false,
  ari: false,
  aschedule: false,
  cn: false,
  ml: false,
  rt: false,
  mppr: false,
  ft: false,
  dtf: false,
  reassessment: false,
  iass: false,
  nass: false,
  tp: false,
  fs: false,
  sp: false,
  ri: false,
  rv: false,
  em: false,
  mars: false,
  mr: false,
  ms: false,
  rmt: false,
  mc: false,
  icm: false,
  prn: false,
  ba: false,
  va: false,
  ma: false,
  ahis: false,
  cf: false,
  df: false,
  uf: false,
  pia: false,
  ptp: false,
  pna: false,
  psp: false,
  pfs: false,
  pri: false,
  pdischarge: false,
  psn: false,
  pa: false,
  pcm: false,
  pprn: false,
  prmt: false,
  pmars: false,
  papp: false,
  pbhpn: false,
  pdp: false,
  pasamc: false,
  pron: false,
};

export const INITIAL_CONTACT_FORM = {
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  address: "",
  title: "",
  dob: "",
  ahcccsId: "",
  diagnosis: "",
  password: "",
  isActive: true,
  accountType: "",
  typeUser: "",
  gender: "",
  facilityId: "",
  permissionPsychiatricProvider: false,
  permissionClaimSubmission: false,
};

export const INITIAL_PATIENT_FIELDS = {
  admitDate: "",
  psychiatricProvider: "",
  pcpProvider: "",
  diet: "",
  fluidRestriction: "",
  allergies: "",
  preferredLanguage: "",
  ethnicity: "",
  admissionStatus: "",
  programLocationAddress: "",
  guardianship: "",
  guardianshipName: "",
  reasonForAdmission: "",
  residentGoals: "",
  residentStrength: "",
  residentBarriers: "",
  allergiesFoodEnvMed: "",
  fallRisk: "",
  triggers: "",
  hobbiesLeisure: "",
  mentalHealthDiagnoses: "",
  medicalDiagnoses: "",
  primaryLanguage: "",
  courtOrderedTreatment: "",
  medicationAllergies: "",
  otherAllergies: "",
  healthPlan: "",
  idNumber: "",
  mentalDiagnosisHistory: "",
  pastSurgeries: "",
  presentingProblem: "",
  residentGoal: "",
  barries: "",
};

export const INITIAL_PERMISSION_CATEGORIES = {
  employeeInfo: undefined,
  intake: undefined,
  contact: undefined,
  document: undefined,
  medical: undefined,
  calendar: undefined,
  clinical: undefined,
  incident: undefined,
  reassessmentCategory: undefined,
};

export const createFieldUpdater = (setter) => (field, value) =>
  setter((prev) => ({ ...prev, [field]: value }));
