/** @format */

export function mapMentalStatusExamFromApi(api = {}) {
  return {
    consistent: api?.apparentAge?.consistent,
    younger: api?.apparentAge?.younger,
    older: api?.apparentAge?.older,
    olderOtherBoolean: api?.apparentAge?.otherComment ? true : false,
    olderOther: api?.apparentAge?.otherComment,
    averageHeight: api?.height?.average,
    short: api?.height?.short,
    tall: api?.height?.tall,
    heigthBoolean: api?.height?.otherComment ? true : false,
    heigthOther: api?.height?.otherComment,
    averageWeight: api?.weight?.average,
    obese: api?.weight?.obese,
    overweight: api?.weight?.overweight,
    thin: api?.weight?.thin,
    emaciated: api?.weight?.emaciated,
    WeightBoolean: api?.weight?.otherComment ? true : false,
    WeightOther: api?.weight?.otherComment,
    casual: api?.attire?.Casual,
    neat: api?.attire?.Neat,
    tattered: api?.attire?.Tattered,
    dirty: api?.attire?.Dirty,
    attireBoolean: api?.attire?.otherComment ? true : false,
    attireOther: api?.attire?.otherComment,
    wellGroomed: api?.grooming?.wellGroomed,
    adequateGrooming: api?.grooming?.adequate,
    unkempt: api?.grooming?.unkempt,
    disheveled: api?.grooming?.disheveled,
    GroomingBoolean: api?.grooming?.otherComment ? true : false,
    GroomingOther: api?.grooming?.otherComment,
    euthymic: api?.Mood?.Euthymic,
    irritable: api?.Mood?.Irritable,
    elevated: api?.Mood?.Elevated,
    depressedMood: api?.Mood?.Depressed,
    anxious: api?.Mood?.Anxious,
    euthymicOtherBoolean: api?.Mood?.otherComment ? true : false,
    euthymicOtherBooleanType: api?.Mood?.otherComment,
    normalRange: api?.Affect?.normalRange,
    depressedAffect: api?.Affect?.Depressed,
    labile: api?.Affect?.Labile,
    constricted: api?.Affect?.Constricted,
    other: api?.Affect?.otherComment ? true : false,
    otherText: api?.Affect?.otherComment,
    appropriate: api?.EyeContact?.Appropriate,
    minimal: api?.EyeContact?.Minimal,
    poor: api?.EyeContact?.Poor,
    adequateEyeContact: api?.EyeContact?.Adequate,
    EyeContactOtherBoolean: api?.EyeContact?.otherComment ? true : false,
    EyeContactOtherBooleanType: api?.EyeContact?.otherComment,
    appropriateCooperation: api?.Cooperation?.Appropriate,
    hostile: api?.Cooperation?.Hostile,
    evasive: api?.Cooperation?.Evasive,
    defensive: api?.Cooperation?.Defensive,
    indifferent: api?.Cooperation?.Indifferent,
    CooperationOtherBoolean: api?.Cooperation?.otherComment ? true : false,
    CooperationOtherBooleanType: api?.Cooperation?.otherComment,
    normalArticulation: api?.Articulation?.Normal,
    unintelligible: api?.Articulation?.Unintelligible,
    mumbled: api?.Articulation?.Mumbled,
    slurred: api?.Articulation?.Slurred,
    stuttered: api?.Articulation?.Stuttered,
    ArticulationOtherBoolean: api?.Articulation?.otherComment ? true : false,
    ArticulationOtherBooleanOther: api?.Articulation?.otherComment,
    normalTone: api?.Tone?.Normal,
    soft: api?.Tone?.Soft,
    loud: api?.Tone?.Loud,
    pressured: api?.Tone?.Pressured,
    ToneOtherBoolean: api?.Tone?.otherComment ? true : false,
    ToneOtherBooleanOther: api?.Tone?.otherComment,
    normalRate: api?.Rate?.Normal,
    slow: api?.Rate?.Slow,
    fast: api?.Rate?.Fast,
    RateOtherBoolean: api?.Rate?.otherComment ? true : false,
    RateOtherBooleanOther: api?.Rate?.otherComment,
    normalQuantity: api?.Quantity?.Normal,
    verbose: api?.Quantity?.Verbose,
    mutism: api?.Quantity?.Mutism,
    QuantityOtherBoolean: api?.Quantity?.otherComment ? true : false,
    QuantityOtherBooleanOther: api?.Quantity?.otherComment,
    normalresponseLatency: api?.responseLatency?.Normal,
    delayed: api?.responseLatency?.Delayed,
    shortened: api?.responseLatency?.Shortened,
    responseLatencyOtherBoolean: api?.responseLatency?.otherComment
      ? true
      : false,
    responseLatencyOtherBooleanOther: api?.responseLatency?.otherComment,
    unremarkablethoughtContent: api?.thoughtContent?.Unremarkable,
    suspicious: api?.thoughtContent?.Suspicious,
    negative: api?.thoughtContent?.Negative,
    concrete: api?.thoughtContent?.Concrete,
    thoughtContentBoolaen: api?.thoughtContent?.otherComment ? true : false,
    thoughtContentOther: api?.thoughtContent?.otherComment,
    logicalCoherent: api?.thoughtProcesses?.logicalCoherent,
    tangential: api?.thoughtProcesses?.Tangential,
    circumstantial: api?.thoughtProcesses?.Circumstantial,
    vague: api?.thoughtProcesses?.Vague,
    thoughtProcessesBoolean: api?.thoughtProcesses?.otherComment ? true : false,
    thoughtProcessesOther: api?.thoughtProcesses?.otherComment,
    noDelusions: api?.Delusions?.No,
    yesPersecutory: api?.Delusions?.YesPersecutory,
    yesSomatic: api?.Delusions?.YesSomatic,
    yesGrandiose: api?.Delusions?.YesGrandiose,
    yesOtherDelusionsBoolean: api?.Delusions?.otherComment ? true : false,
    yesOtherDelusionsText: api?.Delusions?.otherComment,
    unremarkableHallucinations: api?.Hallucinations?.Unremarkable,
    visualHallucinations: api?.Hallucinations?.VisualHallucinations,
    auditoryHallucinations: api?.Hallucinations?.AuditoryHallucinations,
    tactileHallucinations: api?.Hallucinations?.TactileHallucinations,
    yesOtherHallucinationsBoolean: api?.Hallucinations?.otherComment
      ? true
      : false,
    yesOtherHallucinationsText: api?.Hallucinations?.otherComment,
    normalGait: api?.Gait?.Normal,
    staggering: api?.Gait?.Staggering,
    shuffling: api?.Gait?.Shuffling,
    slowGait: api?.Gait?.Slow,
    awkward: api?.Gait?.Awkward,
    gaitOtherBoolen: api?.Gait?.otherComment ? true : false,
    gaitOther: api?.Gait?.otherComment,
    normalPosture: api?.Posture?.Normal,
    relaxed: api?.Posture?.Relaxed,
    rigid: api?.Posture?.Rigid,
    tense: api?.Posture?.Tense,
    slouched: api?.Posture?.Slouched,
    PostureOtherBoolen: api?.Posture?.otherComment ? true : false,
    PostureOther: api?.Posture?.otherComment,
    withinNormalLimits: api?.PsychomotorActivity?.Withinnormallimits,
    calm: api?.PsychomotorActivity?.Calm,
    hyperactive: api?.PsychomotorActivity?.Hyperactive,
    agitated: api?.PsychomotorActivity?.Agitated,
    hypoactive: api?.PsychomotorActivity?.Hypoactive,
    PsychomotorActivityOtherBoolen: api?.PsychomotorActivity?.otherComment
      ? true
      : false,
    PsychomotorActivityOther: api?.PsychomotorActivity?.otherComment,
    none: api?.Mannerisms?.None,
    tics: api?.Mannerisms?.Tics,
    tremorsMannerisms: api?.Mannerisms?.Tremors,
    rocking: api?.Mannerisms?.Rocking,
    picking: api?.Mannerisms?.Picking,
    MannerismsOtherBoolen: api?.Mannerisms?.otherComment ? true : false,
    MannerismsOther: api?.Mannerisms?.otherComment,
    person: api?.orientation?.person,
    place: api?.orientation?.place,
    time: api?.orientation?.time,
    circumstances: api?.orientation?.circumstances,
    goodJudgment: api?.Judgment?.Good,
    fairJudgment: api?.Judgment?.Fair,
    poorJudgment: api?.Insight?.Poor,
    goodInsight: api?.Judgment?.Good,
    fairInsight: api?.Insight?.Fair,
    poorInsight: api?.Insight?.Poor,
    goodMemory: api?.Memory?.Good,
    fairMemory: api?.Memory?.Fair,
    poorMemory: api?.Memory?.Poor,
    intactAbilityToConcentrationOtherBoolean: api?.AbilityToConcentration?.Other
      ? true
      : false,
    intactAbilityToConcentration: api?.AbilityToConcentration?.Intact,
    otherAbilityToConcentration: api?.AbilityToConcentration?.Other,
  };
}
