/** @format */

import { describe, it, expect } from "vitest";
import { buildAssessmentPayloadForResident } from "./residentPayloadMapper";

// NOTE: buildAssessmentPayload compiles a `new Function` whose body reads many
// form-state identifiers as free variables. Those identifiers MUST be present
// as keys in the input object or the generated function throws a ReferenceError
// (only array fields have built-in defaults). So we build a "full" base input
// where every referenced field is defined (undefined) and spread the specific
// values a test cares about on top. This list mirrors the identifiers read by
// payloadMapper.js's function body.
const BASE_FIELD_NAMES = [
  "AbilityToConcentration",
  "Able",
  "Access",
  "AccessComment",
  "AccessYesNo",
  "ActiveWithdrawalSymptoms",
  "Additional",
  "Additional1Description",
  "Additional1icdCode",
  "Adequate",
  "Affect",
  "Agitated",
  "Agitation",
  "Alcohol",
  "Allergies",
  "AllergiesComment",
  "AllergiesYes",
  "Anxiety",
  "AnxietyComment",
  "AnxietyYes",
  "Anxious",
  "Any",
  "Appropriate",
  "Articulation",
  "ArticulationOtherBooleanOther",
  "AuditoryDisturbances",
  "AuditoryHallucinations",
  "Awkward",
  "Bathing",
  "BathingComments",
  "BathingFair",
  "BathingGood",
  "BathingGoodNeedAssist",
  "BathingNotSoGood",
  "Behavior",
  "Benzodiazepines",
  "Bipolar",
  "BipolarComment",
  "BipolarYes",
  "Blood",
  "BonePain",
  "COPD",
  "Calm",
  "Cancer",
  "Care",
  "Casual",
  "Chronic",
  "ChronicPain",
  "ChronicYesNO",
  "Circumstantial",
  "Cocaine",
  "Concrete",
  "Constricted",
  "Cooperation",
  "CooperationOtherBooleanType",
  "Crack",
  "Current",
  "CurrentYesNO",
  "Defensive",
  "Delayed",
  "Delusions",
  "Depressed",
  "Depression",
  "DepressionComment",
  "DepressionYes",
  "Dirty",
  "Diseases",
  "Eating",
  "EatingComments",
  "EatingFair",
  "EatingGood",
  "EatingGoodNeedAssist",
  "EatingNotSoGood",
  "Elevated",
  "Euthymic",
  "Evasive",
  "EyeContact",
  "EyeContactOtherBooleanType",
  "Fair",
  "Family",
  "FamilyYesNO",
  "Fast",
  "Fear",
  "FearComment",
  "FearYesNo",
  "Gait",
  "Good",
  "GooseBumps",
  "Grooming",
  "GroomingComments",
  "GroomingFair",
  "GroomingGood",
  "GroomingGoodNeedAssist",
  "GroomingNotSoGood",
  "GroomingOther",
  "Hallucinations",
  "Hallucinogens",
  "Headache",
  "Heart",
  "Heroin",
  "High",
  "History",
  "Hostile",
  "Housework",
  "HouseworkComments",
  "HouseworkFair",
  "HouseworkGood",
  "HouseworkGoodNeedAssist",
  "HouseworkNotSoGood",
  "Hyperactive",
  "Hypoactive",
  "Indifferent",
  "Infection",
  "Inhalants",
  "Insight",
  "Insomnia",
  "InsomniaComment",
  "InsomniaYes",
  "Intact",
  "Irritable",
  "Judgment",
  "Labile",
  "Liver",
  "LossofMuscleCoordination",
  "LossofMuscleCoordinationOtherType",
  "Loud",
  "Lung",
  "MDMA",
  "Managing",
  "ManagingComments",
  "ManagingFair",
  "ManagingGood",
  "ManagingGoodNeedAssist",
  "ManagingNotSoGood",
  "Mannerisms",
  "MannerismsOther",
  "Marijuana",
  "Memory",
  "Methadone",
  "Methamphetamine",
  "Minimal",
  "Mobility",
  "MobilityComments",
  "MobilityFair",
  "MobilityGood",
  "MobilityGoodNeedAssist",
  "MobilityNotSoGood",
  "Mood",
  "Mumbled",
  "Mutism",
  "Nausea",
  "Neat",
  "Negative",
  "No",
  "None",
  "Normal",
  "Number",
  "OTC",
  "Obsessive",
  "ObsessiveComment",
  "ObsessiveYes",
  "Other",
  "Paranoia",
  "Personality",
  "PersonalityComment",
  "PersonalityYes",
  "Phobias",
  "PhobiasComment",
  "PhobiasYes",
  "Physician",
  "Picking",
  "Poor",
  "Posture",
  "PostureOther",
  "Preparing",
  "PreparingComments",
  "PreparingFair",
  "PreparingGood",
  "PreparingGoodNeedAssist",
  "PreparingNotSoGood",
  "Prescription",
  "Pressure",
  "Pressured",
  "Primary",
  "Prior",
  "PriorComment",
  "PriorYesNo",
  "PsychomotorActivity",
  "PsychomotorActivityOther",
  "Quantity",
  "QuantityOtherBooleanOther",
  "Rate",
  "RateOtherBooleanOther",
  "Recent",
  "RecentComment",
  "RecentYesNo",
  "Relaxed",
  "Religious",
  "ReligiousComment",
  "ReligiousYesNo",
  "ResidentDate",
  "ResidentName",
  "ResidentSignature",
  "Rigid",
  "Rocking",
  "Runningnose",
  "Schizophrenia",
  "SchizophreniaComment",
  "SchizophreniaYes",
  "Secondary",
  "Seizures",
  "Shopping",
  "ShoppingComments",
  "ShoppingFair",
  "ShoppingGood",
  "ShoppingGoodNeedAssist",
  "ShoppingNotSoGood",
  "Shortened",
  "Showering",
  "Shuffling",
  "SignificantFamilyMedicalPsychiatricHistory",
  "Slouched",
  "Slow",
  "Slurred",
  "Soft",
  "Spiritual",
  "SpiritualComment",
  "SpiritualYesNo",
  "Staggering",
  "Stuttered",
  "Substance",
  "SubstanceAbuseComment",
  "SubstanceComment",
  "SubstanceYes",
  "SubstanceYesNo",
  "Supports",
  "SupportsComment",
  "SupportsYesNo",
  "Surgeries",
  "SurgeriesComment",
  "SurgeriesYes",
  "Suspicious",
  "Sweats",
  "Symptoms",
  "SymptomsYesNO",
  "TactileDisturbances",
  "TactileHallucinations",
  "Taking",
  "TakingComments",
  "TakingFair",
  "TakingGood",
  "TakingGoodNeedAssist",
  "TakingNotSoGood",
  "Tangential",
  "Tattered",
  "Tearing",
  "Tense",
  "Terminal",
  "TerminalYesNO",
  "Tertiary",
  "TertiaryDescription",
  "TertiaryIcdCode",
  "Thyroid",
  "Tics",
  "Toileting",
  "ToiletingComments",
  "ToiletingFair",
  "ToiletingGood",
  "ToiletingGoodNeedAssist",
  "ToiletingNotSoGood",
  "Tone",
  "ToneOtherBooleanOther",
  "Tremors",
  "Unintelligible",
  "Unremarkable",
  "Vague",
  "Verbose",
  "VisualDisturbances",
  "VisualDisturbancesOtherType",
  "VisualHallucinations",
  "Vomiting",
  "WeightOther",
  "Willing",
  "WillingComment",
  "WillingYesNo",
  "Withinnormallimits",
  "YesGrandiose",
  "YesPersecutory",
  "YesSomatic",
  "abuse",
  "abusing",
  "abusingComment",
  "abusingYesNo",
  "acceptResident",
  "accessToHealthCareServices",
  "accidentInjury",
  "activeDuty",
  "additionalNotes",
  "adequate",
  "adequateEyeContact",
  "adequateGrooming",
  "adminSignature",
  "adminSignatureDate",
  "adminSignatureTime",
  "admissionStatus",
  "ageOfFirstUse",
  "agitated",
  "ahcccsId",
  "ahcccsNumber",
  "angel",
  "anxious",
  "apparentAge",
  "appropriate",
  "appropriateCooperation",
  "approvedBy",
  "assessmentOn",
  "assessmentType",
  "asthma",
  "attack",
  "attacks",
  "attempt",
  "attire",
  "attireOther",
  "auditoryHallucinations",
  "available",
  "average",
  "averageHeight",
  "averageWeight",
  "awkward",
  "be",
  "behavior",
  "behaviorcuesDropDown",
  "behaviourYesNO",
  "bhpCredentials",
  "bhpDate",
  "bhpInformation",
  "bhpName",
  "bhpSignature",
  "bhpTime",
  "bhrfCriteria",
  "births",
  "brain",
  "budget",
  "calm",
  "casual",
  "childRemovedFromHouse",
  "chronicCommit",
  "circumstances",
  "circumstantial",
  "clinicalSummary",
  "comment",
  "commentCancer",
  "commentDiabety",
  "commentHeart",
  "commentHigh",
  "commentHistory",
  "commentLiver",
  "commentLung",
  "commentSeizures",
  "commentbrain",
  "comments",
  "commit",
  "companyName",
  "compulsive",
  "concrete",
  "condition",
  "conditions",
  "consequences",
  "consistent",
  "constricted",
  "cues",
  "cultural",
  "currentBehavioralIssues",
  "currentStudent",
  "currentStudentLocation",
  "currentThoughtsOfHarmingOthers",
  "currentThoughtsOfHarmingSelf",
  "currentlyEmployed",
  "dateOfAssessment",
  "dateSigned",
  "death",
  "defensive",
  "delayed",
  "depressedAffect",
  "depressedMood",
  "description",
  "diabetes",
  "dirty",
  "disease",
  "disheveled",
  "disorder",
  "divorceSeparation",
  "dob",
  "dust",
  "e",
  "ecstasy",
  "educationalHistory",
  "educationalProblems",
  "elevated",
  "emaciated",
  "emphysema",
  "employmentHistory",
  "employmentLocation",
  "engaged",
  "ethnicity",
  "euthymic",
  "euthymicOtherBooleanType",
  "evasive",
  "fair",
  "fairInsight",
  "fairJudgment",
  "fairMemory",
  "fallRisk",
  "fallRiskExplanation",
  "family",
  "familyProblems",
  "fast",
  "food",
  "frequency",
  "friends",
  "gaitOther",
  "good",
  "goodInsight",
  "goodJudgment",
  "goodMemory",
  "grooming",
  "guardianship",
  "guardianshipPoaPubFidName",
  "handleRiskFactorActivityArray",
  "hasNotified",
  "head",
  "health",
  "healthConditionsYes",
  "healthConditionsYesComment",
  "heart",
  "height",
  "heigthOther",
  "highestEducation",
  "history",
  "hobbiesLeisureActivities",
  "hostile",
  "housingProblems",
  "hygiene",
  "hyperactive",
  "hypoactive",
  "i",
  "icdCode",
  "ideation",
  "ie",
  "ifYesWhere",
  "illness",
  "independentLivingSkills",
  "indifferent",
  "infectionDiseases",
  "injury",
  "intactAbilityToConcentration",
  "interactionWithLegalSystem",
  "intervention",
  "interventionComment",
  "interventionYesNo",
  "irritable",
  "job",
  "keeping",
  "kidney",
  "labile",
  "lack",
  "lastUse",
  "legalHistory",
  "lengthOfSobriety",
  "logicalCoherent",
  "losses",
  "loud",
  "maritalProblems",
  "means",
  "medicalConditions",
  "medicalDiagnoses",
  "medicalEquipmentArray",
  "medicalSurgical",
  "medications",
  "medicine",
  "mentalHealthTreatmentHistory",
  "mentalStatusExam",
  "militaryHistory",
  "militaryService",
  "minimal",
  "money",
  "mumbled",
  "mutism",
  "n",
  "name",
  "neat",
  "needAssist",
  "negative",
  "noDelusions",
  "none",
  "noneReportedOrObserved",
  "normalArticulation",
  "normalGait",
  "normalPosture",
  "normalQuantity",
  "normalRange",
  "normalRate",
  "normalTone",
  "normalresponseLatency",
  "obese",
  "occupationalProblems",
  "of",
  "older",
  "olderOther",
  "or",
  "orientation",
  "other",
  "otherAbilityToConcentration",
  "otherComment",
  "otherConditionArray",
  "otherCurrentNotSoGood",
  "otherSignificantRecentLossesType",
  "otherStressors",
  "otherText",
  "overweight",
  "pain",
  "painChronic",
  "panic",
  "patientId",
  "patient_Id",
  "person",
  "personalInformation",
  "physical",
  "picking",
  "place",
  "please",
  "poor",
  "poorInsight",
  "poorJudgment",
  "poorMemory",
  "powerOfAttorneyStatus",
  "preferredLanguage",
  "pregnancies",
  "pregnanciesComment",
  "pregnanciesYes",
  "pressured",
  "primaryDescription",
  "primaryIcdCode",
  "primarySupportGroup",
  "programLocation",
  "prohibitions",
  "protectiveFactors",
  "protectiveFactorsArray",
  "psychiatricAdditionalDescription",
  "psychiatricAdditionalicdCode",
  "psychiatricDiagnoses",
  "psychiatricDiagnosesArray",
  "psychiatricPrimaryDescription",
  "psychiatricPrimaryIcdCode",
  "psychiatricSecondaryDescription",
  "psychiatricSecondaryicdCode",
  "psychiatricTertiaryDescription",
  "psychiatricTertiaryIcdCode",
  "psychosis",
  "reasonForAdmission",
  "relaxed",
  "religious",
  "residentGauardianSignature",
  "residentGoals",
  "residentGuardianDate",
  "residentGuardianName",
  "residentGuardianTime",
  "residentInformation",
  "residentLimitations",
  "residentName",
  "residentRepresentative",
  "residentStrengths",
  "responseLatency",
  "responseLatencyOtherBooleanOther",
  "rigid",
  "riskComment",
  "riskFactorArray",
  "riskFactors",
  "riskLevel",
  "riskYesNo",
  "rocking",
  "safe",
  "secondaryDescription",
  "secondaryicdCode",
  "selectedValue",
  "selectedValueMedical",
  "selectedValueSpecialPrecautions",
  "self",
  "setNoAndYes",
  "sex",
  "sexualProblems",
  "short",
  "shortened",
  "shuffling",
  "signature",
  "signatures",
  "signedTime",
  "signerId",
  "significantRecentLosses",
  "significantSocialDevelopmentalHistory",
  "slouched",
  "slow",
  "slowGait",
  "slurred",
  "soft",
  "specialEducation",
  "specialPrecautions",
  "specify",
  "staffDate",
  "staffDateTime",
  "staffInformation",
  "staffName",
  "staffSignature",
  "staggering",
  "stressors",
  "stuttered",
  "substanceAbuseDenies",
  "substanceAbuseHistory",
  "substanceAbuseHistoryData",
  "substanceAbuseHistoryDataAgeOfFirstUseAlcohol",
  "substanceAbuseHistoryDataAgeOfFirstUseBenzodiazepines",
  "substanceAbuseHistoryDataAgeOfFirstUseCocaine",
  "substanceAbuseHistoryDataAgeOfFirstUseCrack",
  "substanceAbuseHistoryDataAgeOfFirstUseHallucinogens",
  "substanceAbuseHistoryDataAgeOfFirstUseHeroin",
  "substanceAbuseHistoryDataAgeOfFirstUseInhalants",
  "substanceAbuseHistoryDataAgeOfFirstUseMDMA",
  "substanceAbuseHistoryDataAgeOfFirstUseMarijuana",
  "substanceAbuseHistoryDataAgeOfFirstUseMethadone",
  "substanceAbuseHistoryDataAgeOfFirstUseMethamphetamine",
  "substanceAbuseHistoryDataAgeOfFirstUseOTC",
  "substanceAbuseHistoryDataAgeOfFirstUsePCP",
  "substanceAbuseHistoryDataAgeOfFirstUsePrescription",
  "substanceAbuseHistoryDataFrequencyAlcohol",
  "substanceAbuseHistoryDataFrequencyBenzodiazepines",
  "substanceAbuseHistoryDataFrequencyCocaine",
  "substanceAbuseHistoryDataFrequencyCrack",
  "substanceAbuseHistoryDataFrequencyHallucinogens",
  "substanceAbuseHistoryDataFrequencyHeroin",
  "substanceAbuseHistoryDataFrequencyInhalants",
  "substanceAbuseHistoryDataFrequencyMDMA",
  "substanceAbuseHistoryDataFrequencyMarijuana",
  "substanceAbuseHistoryDataFrequencyMethadone",
  "substanceAbuseHistoryDataFrequencyMethamphetamine",
  "substanceAbuseHistoryDataFrequencyOTC",
  "substanceAbuseHistoryDataFrequencyPCP",
  "substanceAbuseHistoryDataFrequencyPrescription",
  "substanceAbuseHistoryDataLastUseAlcohol",
  "substanceAbuseHistoryDataLastUseBenzodiazepines",
  "substanceAbuseHistoryDataLastUseCocaine",
  "substanceAbuseHistoryDataLastUseCrack",
  "substanceAbuseHistoryDataLastUseHallucinogens",
  "substanceAbuseHistoryDataLastUseHeroin",
  "substanceAbuseHistoryDataLastUseInhalants",
  "substanceAbuseHistoryDataLastUseMDMA",
  "substanceAbuseHistoryDataLastUseMarijuana",
  "substanceAbuseHistoryDataLastUseMethadone",
  "substanceAbuseHistoryDataLastUseMethamphetamine",
  "substanceAbuseHistoryDataLastUseOTC",
  "substanceAbuseHistoryDataLastUsePCP",
  "substanceAbuseHistoryDataLastUsePrescription",
  "substanceAbuseHistoryDataLengthOfSobrietyAlcohol",
  "substanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines",
  "substanceAbuseHistoryDataLengthOfSobrietyCocaine",
  "substanceAbuseHistoryDataLengthOfSobrietyCrack",
  "substanceAbuseHistoryDataLengthOfSobrietyHallucinogens",
  "substanceAbuseHistoryDataLengthOfSobrietyHeroin",
  "substanceAbuseHistoryDataLengthOfSobrietyInhalants",
  "substanceAbuseHistoryDataLengthOfSobrietyMDMA",
  "substanceAbuseHistoryDataLengthOfSobrietyMarijuana",
  "substanceAbuseHistoryDataLengthOfSobrietyMethadone",
  "substanceAbuseHistoryDataLengthOfSobrietyMethamphetamine",
  "substanceAbuseHistoryDataLengthOfSobrietyOTC",
  "substanceAbuseHistoryDataLengthOfSobrietyPCP",
  "substanceAbuseHistoryDataLengthOfSobrietyPrescription",
  "substanceUseInHome",
  "suicidal",
  "suicidalIdeation",
  "suicidalIdeationSeverity",
  "suicidalIdeationUrgency",
  "suicide",
  "support",
  "suspicious",
  "symptomsOfPsychosisDropDown",
  "tactileHallucinations",
  "tall",
  "tangential",
  "tattered",
  "tense",
  "thin",
  "thoughtContent",
  "thoughtContentOther",
  "thoughtProcesses",
  "thoughtProcessesOther",
  "thyroidDisorder",
  "tics",
  "time",
  "to",
  "todayDate",
  "trauma",
  "traumatic",
  "treatmentRecommendations",
  "tremorsMannerisms",
  "triggers",
  "type",
  "typeArray",
  "typeOfLoss",
  "typeOfServiceArray",
  "types",
  "unintelligible",
  "unkempt",
  "unremarkableHallucinations",
  "unremarkablethoughtContent",
  "use",
  "vague",
  "verbose",
  "violentActsAgainstPersonFamily",
  "visualHallucinations",
  "weapon",
  "weight",
  "wellGroomed",
  "withinNormalLimits",
  "workHistory",
  "yes",
  "yesCancer",
  "yesChronic",
  "yesDiabetes",
  "yesGrandiose",
  "yesHeart",
  "yesHigh",
  "yesHistory",
  "yesLiver",
  "yesLung",
  "yesNo",
  "yesOtherDelusionsText",
  "yesOtherHallucinationsText",
  "yesPersecutory",
  "yesSeizures",
  "yesSomatic",
  "yesThyroid",
  "yesbrain",
  "younger",
];

// Build a fully-populated base input so the generated function's free-variable
// reads never throw. Specific tests spread their own values on top.
// These fields have `.forEach`/spread applied in the function body, so they
// must be arrays. The source's ARRAY_PAYLOAD_DEFAULTS supplies [] for them, but
// our explicit `undefined` base values would override those defaults — so seed
// them as [] here.
const ARRAY_FIELD_NAMES = [
  "SignificantFamilyMedicalPsychiatricHistory",
  "admissionStatus",
  "selectedValue",
  "selectedValueMedical",
  "selectedValueSpecialPrecautions",
  "thyroidDisorder",
  "infectionDiseases",
  "reasonForAdmission",
  "behaviorcuesDropDown",
  "symptomsOfPsychosisDropDown",
  "residentStrengths",
  "otherConditionArray",
  "typeArray",
  "handleRiskFactorActivityArray",
  "riskFactorArray",
  "protectiveFactorsArray",
  "psychiatricDiagnosesArray",
];

function makeInput(overrides = {}) {
  const base = {};
  for (const key of BASE_FIELD_NAMES) base[key] = undefined;
  for (const key of ARRAY_FIELD_NAMES) base[key] = [];
  // `id` and `signers` are also read by the function body.
  base.id = undefined;
  base.signers = undefined;
  return { ...base, ...overrides };
}

// This mapper wraps buildAssessmentPayload and applies the resident-portal
// legacy behavior: every medicalConditions row gets `state: true`.
describe("buildAssessmentPayloadForResident", () => {
  it("returns the payload shape for a default-populated input", () => {
    const data = buildAssessmentPayloadForResident(makeInput());

    expect(data).toBeTypeOf("object");
    expect(Array.isArray(data.medicalConditions)).toBe(true);
    expect(Array.isArray(data.riskFactors)).toBe(true);
    expect(Array.isArray(data.protectiveFactors)).toBe(true);
    expect(data.mentalStatusExam).toBeTypeOf("object");
    expect(data.ActiveWithdrawalSymptoms).toBeTypeOf("object");
  });

  it("adds state:true to every medicalConditions row (legacy resident behavior)", () => {
    const data = buildAssessmentPayloadForResident(makeInput());

    expect(data.medicalConditions.length).toBeGreaterThan(0);
    // WHY: the resident wrapper's sole job is to stamp state:true on each row.
    expect(data.medicalConditions.every((item) => item.state === true)).toBe(
      true,
    );
  });

  it("preserves the original medicalConditions fields while adding state", () => {
    const data = buildAssessmentPayloadForResident(
      makeInput({ yesDiabetes: "Yes", commentDiabety: "controlled" }),
    );

    const diabetes = data.medicalConditions.find(
      (c) => c.condition === "diabetes",
    );
    expect(diabetes).toBeDefined();
    expect(diabetes.yes).toBe("Yes");
    expect(diabetes.comments).toBe("controlled");
    expect(diabetes.state).toBe(true); // added by the resident wrapper
  });

  it("merges caller-supplied otherConditionArray rows and stamps them too", () => {
    const data = buildAssessmentPayloadForResident(
      makeInput({
        otherConditionArray: [
          { condition: "custom", yes: "Yes", comments: "extra" },
        ],
      }),
    );

    const custom = data.medicalConditions.find((c) => c.condition === "custom");
    expect(custom).toBeDefined();
    expect(custom.state).toBe(true);
    // Every row, including appended custom rows, must carry state.
    expect(data.medicalConditions.every((c) => c.state === true)).toBe(true);
  });

  it("flattens select-style array fields into plain value arrays", () => {
    const data = buildAssessmentPayloadForResident(
      makeInput({
        reasonForAdmission: [{ value: "psych" }, { value: "detox" }],
        residentStrengths: [{ value: "resilient" }],
      }),
    );

    expect(data.reasonForAdmission).toEqual(["psych", "detox"]);
    expect(data.residentStrengths).toEqual(["resilient"]);
  });

  it("maps scalar identity fields straight through", () => {
    const data = buildAssessmentPayloadForResident(
      makeInput({
        patient_Id: "res-test-001",
        residentName: "Test Patient",
        ahcccsId: "MRN-TEST-001",
      }),
    );

    expect(data.patientId).toBe("res-test-001");
    expect(data.residentName).toBe("Test Patient");
    expect(data.ahcccsNumber).toBe("MRN-TEST-001");
  });

  it("transforms signers when no id is present (new assessment)", () => {
    const data = buildAssessmentPayloadForResident(
      makeInput({
        signers: [
          { value: "emp-test-001", label: "Test Staff", type: "staff" },
        ],
      }),
    );

    expect(data.signers).toEqual([
      {
        signerId: "emp-test-001",
        name: "Test Staff",
        signature: "",
        dateSigned: "",
        signedTime: "",
        type: "staff",
      },
    ]);
  });

  it("passes signers through unchanged when an id is present (edit mode)", () => {
    const existing = [{ signerId: "emp-test-001", name: "Test Staff" }];
    const data = buildAssessmentPayloadForResident(
      makeInput({ id: "assessment-1", signers: existing }),
    );

    expect(data.signers).toEqual(existing);
  });

  it("does not mutate medicalConditions when the field is not an array", () => {
    // buildAssessmentPayload always produces an array here, but guard the
    // documented Array.isArray branch: a non-array stays untouched.
    const data = buildAssessmentPayloadForResident(makeInput());
    expect(Array.isArray(data.medicalConditions)).toBe(true);
    // sanity: state stamping only happened because it was an array
    expect(data.medicalConditions[0].state).toBe(true);
  });
});
