/* eslint-disable no-unused-vars */
/** @format */

import React from "react";
import { Row, Col, Form, Table, Button, Card } from "react-bootstrap";
import { AiFillDelete } from "react-icons/ai";
import SelectSinglePrint from "../common/SelectSinglePrint";
// import "./ia-table-field.css";

/**
 * Substance abuse history checkboxes and substance use table.
 */
export default function SubstanceAbuseSection(props) {
  const {
    OtherlengthOfSobrifty,
    canDelete,
    handleKeyOtherlengthOfSobrifty,
    handleKeyotherFrequancy,
    handleKeyotherLastUse,
    handleKeysubstanceAbuseHistoryDataFrequencyAlcohol,
    handleKeysubstanceAbuseHistoryDataFrequencyBenzodiazepines,
    handleKeysubstanceAbuseHistoryDataFrequencyCocaine,
    handleKeysubstanceAbuseHistoryDataFrequencyCrack,
    handleKeysubstanceAbuseHistoryDataFrequencyHallucinogens,
    handleKeysubstanceAbuseHistoryDataFrequencyHeroin,
    handleKeysubstanceAbuseHistoryDataFrequencyInhalants,
    handleKeysubstanceAbuseHistoryDataFrequencyMDMA,
    handleKeysubstanceAbuseHistoryDataFrequencyMarijuana,
    handleKeysubstanceAbuseHistoryDataFrequencyMethadone,
    handleKeysubstanceAbuseHistoryDataFrequencyMethamphetamine,
    handleKeysubstanceAbuseHistoryDataFrequencyOTC,
    handleKeysubstanceAbuseHistoryDataFrequencyPCP,
    handleKeysubstanceAbuseHistoryDataFrequencyPrescription,
    handleKeysubstanceAbuseHistoryDataLastUseAlcohol,
    handleKeysubstanceAbuseHistoryDataLastUseBenzodiazepines,
    handleKeysubstanceAbuseHistoryDataLastUseCocaine,
    handleKeysubstanceAbuseHistoryDataLastUseCrack,
    handleKeysubstanceAbuseHistoryDataLastUseHallucinogens,
    handleKeysubstanceAbuseHistoryDataLastUseHeroin,
    handleKeysubstanceAbuseHistoryDataLastUseInhalants,
    handleKeysubstanceAbuseHistoryDataLastUseMDMA,
    handleKeysubstanceAbuseHistoryDataLastUseMarijuana,
    handleKeysubstanceAbuseHistoryDataLastUseMethadone,
    handleKeysubstanceAbuseHistoryDataLastUseMethamphetamine,
    handleKeysubstanceAbuseHistoryDataLastUseOTC,
    handleKeysubstanceAbuseHistoryDataLastUsePCP,
    handleKeysubstanceAbuseHistoryDataLastUsePrescription,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyAlcohol,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyCocaine,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyCrack,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyHallucinogens,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyHeroin,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyInhalants,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyMDMA,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyMarijuana,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyMethadone,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyMethamphetamine,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyOTC,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyPCP,
    handleKeysubstanceAbuseHistoryDataLengthOfSobrietyPrescription,
    handleOtherlengthOfSobrifty,
    handleTypeOfArray,
    handleotherFrequancy,
    handleotherLastUse,
    handlersubstanceAbuseHistoryDataFrequencyAlcohol,
    handlersubstanceAbuseHistoryDataLastUseAlcohol,
    handlersubstanceAbuseHistoryDataLengthOfSobrietyAlcohol,
    handlesubstanceAbuseHistoryDataFrequencyBenzodiazepines,
    handlesubstanceAbuseHistoryDataFrequencyCocaine,
    handlesubstanceAbuseHistoryDataFrequencyCrack,
    handlesubstanceAbuseHistoryDataFrequencyHallucinogens,
    handlesubstanceAbuseHistoryDataFrequencyHeroin,
    handlesubstanceAbuseHistoryDataFrequencyInhalants,
    handlesubstanceAbuseHistoryDataFrequencyMDMA,
    handlesubstanceAbuseHistoryDataFrequencyMarijuana,
    handlesubstanceAbuseHistoryDataFrequencyMethadone,
    handlesubstanceAbuseHistoryDataFrequencyMethamphetamine,
    handlesubstanceAbuseHistoryDataFrequencyOTC,
    handlesubstanceAbuseHistoryDataFrequencyPCP,
    handlesubstanceAbuseHistoryDataFrequencyPrescription,
    handlesubstanceAbuseHistoryDataLastUseBenzodiazepines,
    handlesubstanceAbuseHistoryDataLastUseCrack,
    handlesubstanceAbuseHistoryDataLastUseHeroin,
    handlesubstanceAbuseHistoryDataLastUseInhalants,
    handlesubstanceAbuseHistoryDataLastUseMDMA,
    handlesubstanceAbuseHistoryDataLastUseMarijuana,
    handlesubstanceAbuseHistoryDataLastUseMethadone,
    handlesubstanceAbuseHistoryDataLastUseMethamphetamine,
    handlesubstanceAbuseHistoryDataLastUsePrescription,
    handlesubstanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines,
    handlesubstanceAbuseHistoryDataLengthOfSobrietyCocaine,
    handlesubstanceAbuseHistoryDataLengthOfSobrietyCrack,
    handlesubstanceAbuseHistoryDataLengthOfSobrietyHallucinogens,
    handlesubstanceAbuseHistoryDataLengthOfSobrietyHeroin,
    handlesubstanceAbuseHistoryDataLengthOfSobrietyInhalants,
    handlesubstanceAbuseHistoryDataLengthOfSobrietyMDMA,
    handlesubstanceAbuseHistoryDataLengthOfSobrietyMarijuana,
    handlesubstanceAbuseHistoryDataLengthOfSobrietyMethamphetamine,
    handlesubstanceAbuseHistoryDataLengthOfSobrietyOTC,
    handlesubstanceAbuseHistoryDataLengthOfSobrietyPCP,
    hnadlesubstanceAbuseHistoryDataLastUseCocaine,
    hnadlesubstanceAbuseHistoryDataLastUseHallucinogens,
    hnadlesubstanceAbuseHistoryDataLastUseOTC,
    hnadlesubstanceAbuseHistoryDataLastUsePCP,
    hnadlesubstanceAbuseHistoryDataLengthOfSobrietyMethadone,
    hnadlesubstanceAbuseHistoryDataLengthOfSobrietyPrescription,
    id,
    optionOtherlengthOfSobrifty,
    optionotherFrequancy,
    optionotherLastUse,
    optionsubstanceAbuseHistoryDataFrequencyBenzodiazepines,
    optionsubstanceAbuseHistoryDataFrequencyCocaine,
    optionsubstanceAbuseHistoryDataFrequencyCrack,
    optionsubstanceAbuseHistoryDataFrequencyHallucinogens,
    optionsubstanceAbuseHistoryDataFrequencyHeroin,
    optionsubstanceAbuseHistoryDataFrequencyInhalants,
    optionsubstanceAbuseHistoryDataFrequencyMDMA,
    optionsubstanceAbuseHistoryDataFrequencyMarijuana,
    optionsubstanceAbuseHistoryDataFrequencyMethadone,
    optionsubstanceAbuseHistoryDataFrequencyMethamphetamine,
    optionsubstanceAbuseHistoryDataFrequencyOTC,
    optionsubstanceAbuseHistoryDataFrequencyPCP,
    optionsubstanceAbuseHistoryDataFrequencyPrescription,
    optionsubstanceAbuseHistoryDataLastUseBenzodiazepines,
    optionsubstanceAbuseHistoryDataLastUseCocaine,
    optionsubstanceAbuseHistoryDataLastUseCrack,
    optionsubstanceAbuseHistoryDataLastUseHallucinogens,
    optionsubstanceAbuseHistoryDataLastUseHeroin,
    optionsubstanceAbuseHistoryDataLastUseInhalants,
    optionsubstanceAbuseHistoryDataLastUseMDMA,
    optionsubstanceAbuseHistoryDataLastUseMarijuana,
    optionsubstanceAbuseHistoryDataLastUseMethadone,
    optionsubstanceAbuseHistoryDataLastUseMethamphetamine,
    optionsubstanceAbuseHistoryDataLastUseOTC,
    optionsubstanceAbuseHistoryDataLastUsePCP,
    optionsubstanceAbuseHistoryDataLastUsePrescription,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyAlcohol,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyCocaine,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyCrack,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyHallucinogens,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyHeroin,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyInhalants,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyMDMA,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyMarijuana,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyMethadone,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyMethamphetamine,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyOTC,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyPCP,
    optionsubstanceAbuseHistoryDataLengthOfSobrietyPrescription,
    otherAgeOfFirstUse,
    otherFrequancy,
    otherLastUse,
    otherTypeOther,
    removeTypeArray,
    selectedsubstanceAbuseHistoryDataFrequencyAlcohol,
    selectedsubstanceAbuseHistoryDataLastUseAlcohol,
    setOtherAgeOfFirstUse,
    setOtherTypeOther,
    setSubstanceAbuseDenies,
    setSubstanceAbuseHistory,
    setSubstanceAbuseHistoryDataAgeOfFirstUseAlcohol,
    setSubstanceAbuseHistoryDataAgeOfFirstUseBenzodiazepines,
    setSubstanceAbuseHistoryDataAgeOfFirstUseCocaine,
    setSubstanceAbuseHistoryDataAgeOfFirstUseCrack,
    setSubstanceAbuseHistoryDataAgeOfFirstUseHallucinogens,
    setSubstanceAbuseHistoryDataAgeOfFirstUseHeroin,
    setSubstanceAbuseHistoryDataAgeOfFirstUseInhalants,
    setSubstanceAbuseHistoryDataAgeOfFirstUseMDMA,
    setSubstanceAbuseHistoryDataAgeOfFirstUseMarijuana,
    setSubstanceAbuseHistoryDataAgeOfFirstUseMethadone,
    setSubstanceAbuseHistoryDataAgeOfFirstUseMethamphetamine,
    setSubstanceAbuseHistoryDataAgeOfFirstUseOTC,
    setSubstanceAbuseHistoryDataAgeOfFirstUsePCP,
    setSubstanceAbuseHistoryDataAgeOfFirstUsePrescription,
    substanceAbuseDenies,
    substanceAbuseHistory,
    substanceAbuseHistoryDataAgeOfFirstUseAlcohol,
    substanceAbuseHistoryDataAgeOfFirstUseBenzodiazepines,
    substanceAbuseHistoryDataAgeOfFirstUseCocaine,
    substanceAbuseHistoryDataAgeOfFirstUseCrack,
    substanceAbuseHistoryDataAgeOfFirstUseHallucinogens,
    substanceAbuseHistoryDataAgeOfFirstUseHeroin,
    substanceAbuseHistoryDataAgeOfFirstUseInhalants,
    substanceAbuseHistoryDataAgeOfFirstUseMDMA,
    substanceAbuseHistoryDataAgeOfFirstUseMarijuana,
    substanceAbuseHistoryDataAgeOfFirstUseMethadone,
    substanceAbuseHistoryDataAgeOfFirstUseMethamphetamine,
    substanceAbuseHistoryDataAgeOfFirstUseOTC,
    substanceAbuseHistoryDataAgeOfFirstUsePCP,
    substanceAbuseHistoryDataAgeOfFirstUsePrescription,
    substanceAbuseHistoryDataFrequencyAlcohol,
    substanceAbuseHistoryDataFrequencyBenzodiazepines,
    substanceAbuseHistoryDataFrequencyCocaine,
    substanceAbuseHistoryDataFrequencyCrack,
    substanceAbuseHistoryDataFrequencyHallucinogens,
    substanceAbuseHistoryDataFrequencyHeroin,
    substanceAbuseHistoryDataFrequencyInhalants,
    substanceAbuseHistoryDataFrequencyMDMA,
    substanceAbuseHistoryDataFrequencyMarijuana,
    substanceAbuseHistoryDataFrequencyMethadone,
    substanceAbuseHistoryDataFrequencyMethamphetamine,
    substanceAbuseHistoryDataFrequencyOTC,
    substanceAbuseHistoryDataFrequencyPCP,
    substanceAbuseHistoryDataFrequencyPrescription,
    substanceAbuseHistoryDataLastUseAlcohol,
    substanceAbuseHistoryDataLastUseBenzodiazepines,
    substanceAbuseHistoryDataLastUseCocaine,
    substanceAbuseHistoryDataLastUseCrack,
    substanceAbuseHistoryDataLastUseHallucinogens,
    substanceAbuseHistoryDataLastUseHeroin,
    substanceAbuseHistoryDataLastUseInhalants,
    substanceAbuseHistoryDataLastUseMDMA,
    substanceAbuseHistoryDataLastUseMarijuana,
    substanceAbuseHistoryDataLastUseMethadone,
    substanceAbuseHistoryDataLastUseMethamphetamine,
    substanceAbuseHistoryDataLastUseOTC,
    substanceAbuseHistoryDataLastUsePCP,
    substanceAbuseHistoryDataLastUsePrescription,
    substanceAbuseHistoryDataLengthOfSobrietyAlcohol,
    substanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines,
    substanceAbuseHistoryDataLengthOfSobrietyCocaine,
    substanceAbuseHistoryDataLengthOfSobrietyCrack,
    substanceAbuseHistoryDataLengthOfSobrietyHallucinogens,
    substanceAbuseHistoryDataLengthOfSobrietyHeroin,
    substanceAbuseHistoryDataLengthOfSobrietyInhalants,
    substanceAbuseHistoryDataLengthOfSobrietyMDMA,
    substanceAbuseHistoryDataLengthOfSobrietyMarijuana,
    substanceAbuseHistoryDataLengthOfSobrietyMethadone,
    substanceAbuseHistoryDataLengthOfSobrietyMethamphetamine,
    substanceAbuseHistoryDataLengthOfSobrietyOTC,
    substanceAbuseHistoryDataLengthOfSobrietyPCP,
    substanceAbuseHistoryDataLengthOfSobrietyPrescription,
    typeArray,
  } = props;

  return (
    <>
      <Row className="mb-3">
        <Col xs={12} sm={12}>
          <Card body className="mb-3">
            <Form.Group>
              <div className="radio-inline">
                <Form.Check
                  inline
                  label="Substance Abuse history"
                  type="checkbox"
                  id="substanceAbuseHistory"
                  checked={substanceAbuseHistory}
                  onChange={() =>
                    setSubstanceAbuseHistory(!substanceAbuseHistory)
                  }
                />
                <Form.Check
                  inline
                  label="Denies"
                  type="checkbox"
                  id="substanceAbuseDenies"
                  checked={substanceAbuseDenies}
                  onChange={() =>
                    setSubstanceAbuseDenies(!substanceAbuseDenies)
                  }
                />
              </div>
            </Form.Group>
          </Card>
        </Col>
      </Row>
      <Row>
        <Col xs={12} md="12">
          <Table
            responsive="lg"
            bordered
            className={`table-fix-layout ${!substanceAbuseHistoryDataAgeOfFirstUseAlcohol && !substanceAbuseHistoryDataLastUseAlcohol && !substanceAbuseHistoryDataFrequencyAlcohol && !substanceAbuseHistoryDataAgeOfFirstUseBenzodiazepines && !substanceAbuseHistoryDataLastUseBenzodiazepines && !substanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines && !substanceAbuseHistoryDataFrequencyBenzodiazepines && !substanceAbuseHistoryDataAgeOfFirstUseCrack && !substanceAbuseHistoryDataLastUseCrack && !substanceAbuseHistoryDataFrequencyCrack && !substanceAbuseHistoryDataAgeOfFirstUseHeroin && !substanceAbuseHistoryDataLastUseHeroin && !substanceAbuseHistoryDataFrequencyHeroin && !substanceAbuseHistoryDataAgeOfFirstUseInhalants && !substanceAbuseHistoryDataLastUseInhalants && !substanceAbuseHistoryDataFrequencyInhalants && !substanceAbuseHistoryDataAgeOfFirstUseMarijuana && !substanceAbuseHistoryDataLastUseMarijuana && !substanceAbuseHistoryDataFrequencyMarijuana && !substanceAbuseHistoryDataAgeOfFirstUseMethamphetamine && !substanceAbuseHistoryDataLastUseMethamphetamine && !substanceAbuseHistoryDataFrequencyMethamphetamine && !substanceAbuseHistoryDataAgeOfFirstUseMethadone && !substanceAbuseHistoryDataLastUseMethadone && !substanceAbuseHistoryDataAgeOfFirstUseMDMA && !substanceAbuseHistoryDataLastUseMDMA && !substanceAbuseHistoryDataFrequencyMDMA && !substanceAbuseHistoryDataAgeOfFirstUsePCP && !substanceAbuseHistoryDataLastUsePCP && !substanceAbuseHistoryDataFrequencyPCP && !substanceAbuseHistoryDataAgeOfFirstUsePrescription && !substanceAbuseHistoryDataLastUsePrescription && !substanceAbuseHistoryDataFrequencyPrescription && !substanceAbuseHistoryDataAgeOfFirstUseOTC && !substanceAbuseHistoryDataLastUseOTC && !substanceAbuseHistoryDataFrequencyOTC && !otherTypeOther && !otherAgeOfFirstUse && !otherLastUse && "table-row-hinde-print"}`}
          >
            <thead
              className={`overflow-clip fixed-table-data ${!substanceAbuseHistoryDataAgeOfFirstUseAlcohol && !substanceAbuseHistoryDataLastUseAlcohol && !substanceAbuseHistoryDataFrequencyAlcohol && !substanceAbuseHistoryDataAgeOfFirstUseBenzodiazepines && !substanceAbuseHistoryDataLastUseBenzodiazepines && !substanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines && !substanceAbuseHistoryDataFrequencyBenzodiazepines && !substanceAbuseHistoryDataAgeOfFirstUseCrack && !substanceAbuseHistoryDataLastUseCrack && !substanceAbuseHistoryDataFrequencyCrack && !substanceAbuseHistoryDataAgeOfFirstUseHeroin && !substanceAbuseHistoryDataLastUseHeroin && !substanceAbuseHistoryDataFrequencyHeroin && !substanceAbuseHistoryDataAgeOfFirstUseInhalants && !substanceAbuseHistoryDataLastUseInhalants && !substanceAbuseHistoryDataFrequencyInhalants && !substanceAbuseHistoryDataAgeOfFirstUseMarijuana && !substanceAbuseHistoryDataLastUseMarijuana && !substanceAbuseHistoryDataFrequencyMarijuana && !substanceAbuseHistoryDataAgeOfFirstUseMethamphetamine && !substanceAbuseHistoryDataLastUseMethamphetamine && !substanceAbuseHistoryDataFrequencyMethamphetamine && !substanceAbuseHistoryDataAgeOfFirstUseMethadone && !substanceAbuseHistoryDataLastUseMethadone && !substanceAbuseHistoryDataAgeOfFirstUseMDMA && !substanceAbuseHistoryDataLastUseMDMA && !substanceAbuseHistoryDataFrequencyMDMA && !substanceAbuseHistoryDataAgeOfFirstUsePCP && !substanceAbuseHistoryDataLastUsePCP && !substanceAbuseHistoryDataFrequencyPCP && !substanceAbuseHistoryDataAgeOfFirstUsePrescription && !substanceAbuseHistoryDataLastUsePrescription && !substanceAbuseHistoryDataFrequencyPrescription && !substanceAbuseHistoryDataAgeOfFirstUseOTC && !substanceAbuseHistoryDataLastUseOTC && !substanceAbuseHistoryDataFrequencyOTC && !otherTypeOther && !otherAgeOfFirstUse && !otherLastUse && "table-row-hinde-print"}`}
            >
              <tr>
                <th>Type</th>
                <th>Age of First use</th>
                <th>Last Use</th>
                <th>Frequency </th>
                <th>Length of Sobriety</th>
              </tr>
            </thead>
            <tbody>
              <tr
                className={`${!(substanceAbuseHistoryDataAgeOfFirstUseAlcohol || substanceAbuseHistoryDataLastUseAlcohol || substanceAbuseHistoryDataFrequencyAlcohol) && "table-row-hinde-print"}`}
              >
                <td>Alcohol</td>
                <td>
                  <Form.Control
                    as="textarea"
                    className={`ia-table-field ${!substanceAbuseHistoryDataAgeOfFirstUseAlcohol && "table-row-hinde-print"}`}
                    type="text"
                    rows="1"
                    placeholder=""
                    value={substanceAbuseHistoryDataAgeOfFirstUseAlcohol}
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUseAlcohol(
                        e.target.value,
                      )
                    }
                  ></Form.Control>
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUseAlcohol}
                    onChange={handlersubstanceAbuseHistoryDataLastUseAlcohol}
                    options={selectedsubstanceAbuseHistoryDataLastUseAlcohol}
                    isCreatable={true}
                    onKeyDown={handleKeysubstanceAbuseHistoryDataLastUseAlcohol}
                  />
                </td>

                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyAlcohol}
                    onChange={handlersubstanceAbuseHistoryDataFrequencyAlcohol}
                    options={selectedsubstanceAbuseHistoryDataFrequencyAlcohol}
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataFrequencyAlcohol
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLengthOfSobrietyAlcohol}
                    onChange={
                      handlersubstanceAbuseHistoryDataLengthOfSobrietyAlcohol
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLengthOfSobrietyAlcohol
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyAlcohol
                    }
                  />
                </td>
              </tr>

              <tr
                className={`${(!substanceAbuseHistoryDataAgeOfFirstUseBenzodiazepines || !substanceAbuseHistoryDataLastUseBenzodiazepines || !substanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines || !substanceAbuseHistoryDataFrequencyBenzodiazepines) && "table-row-hinde-print"}`}
              >
                <td>Benzodiazepines</td>
                <td>
                  <Form.Control
                    as="textarea"
                    className={`ia-table-field ${!substanceAbuseHistoryDataAgeOfFirstUseBenzodiazepines && "table-row-hinde-print"}`}
                    type="text"
                    rows="1"
                    placeholder=""
                    value={
                      substanceAbuseHistoryDataAgeOfFirstUseBenzodiazepines
                    }
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUseBenzodiazepines(
                        e.target.value,
                      )
                    }
                  ></Form.Control>
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUseBenzodiazepines}
                    onChange={
                      handlesubstanceAbuseHistoryDataLastUseBenzodiazepines
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLastUseBenzodiazepines
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLastUseBenzodiazepines
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyBenzodiazepines}
                    onChange={
                      handlesubstanceAbuseHistoryDataFrequencyBenzodiazepines
                    }
                    options={
                      optionsubstanceAbuseHistoryDataFrequencyBenzodiazepines
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataFrequencyBenzodiazepines
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={
                      substanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines
                    }
                    onChange={
                      handlesubstanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines
                    }
                  />
                </td>
              </tr>
              <tr
                className={`${!substanceAbuseHistoryDataAgeOfFirstUseCrack && !substanceAbuseHistoryDataLastUseCrack && !substanceAbuseHistoryDataFrequencyCrack && "table-row-hinde-print"}`}
              >
                <td>Crack</td>
                <td>
                  <Form.Control
                    as="textarea"
                    className={`ia-table-field ${!substanceAbuseHistoryDataAgeOfFirstUseCrack && "hidePrint"}`}
                    type="text"
                    rows="1"
                    placeholder=""
                    value={substanceAbuseHistoryDataAgeOfFirstUseCrack}
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUseCrack(
                        e.target.value,
                      )
                    }
                  ></Form.Control>
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUseCrack}
                    onChange={handlesubstanceAbuseHistoryDataLastUseCrack}
                    options={optionsubstanceAbuseHistoryDataLastUseCrack}
                    isCreatable={true}
                    onKeyDown={handleKeysubstanceAbuseHistoryDataLastUseCrack}
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyCrack}
                    onChange={handlesubstanceAbuseHistoryDataFrequencyCrack}
                    options={optionsubstanceAbuseHistoryDataFrequencyCrack}
                    isCreatable={true}
                    onKeyDown={handleKeysubstanceAbuseHistoryDataFrequencyCrack}
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLengthOfSobrietyCrack}
                    onChange={
                      handlesubstanceAbuseHistoryDataLengthOfSobrietyCrack
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLengthOfSobrietyCrack
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyCrack
                    }
                  />
                </td>
              </tr>
              <tr
                className={`${!substanceAbuseHistoryDataAgeOfFirstUseHeroin && !substanceAbuseHistoryDataLastUseHeroin && !substanceAbuseHistoryDataFrequencyHeroin && "table-row-hinde-print"}`}
              >
                <td>Heroin</td>
                <td>
                  <Form.Control
                    as="textarea"
                    type="text"
                    className={`ia-table-field ${!substanceAbuseHistoryDataAgeOfFirstUseHeroin && "hidePrint"}`}
                    rows="1"
                    placeholder=""
                    value={substanceAbuseHistoryDataAgeOfFirstUseHeroin}
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUseHeroin(
                        e.target.value,
                      )
                    }
                  ></Form.Control>
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUseHeroin}
                    onChange={handlesubstanceAbuseHistoryDataLastUseHeroin}
                    options={optionsubstanceAbuseHistoryDataLastUseHeroin}
                    isCreatable={true}
                    onKeyDown={handleKeysubstanceAbuseHistoryDataLastUseHeroin}
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyHeroin}
                    onChange={handlesubstanceAbuseHistoryDataFrequencyHeroin}
                    options={optionsubstanceAbuseHistoryDataFrequencyHeroin}
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataFrequencyHeroin
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLengthOfSobrietyHeroin}
                    onChange={
                      handlesubstanceAbuseHistoryDataLengthOfSobrietyHeroin
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLengthOfSobrietyHeroin
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyHeroin
                    }
                  />
                </td>
              </tr>
              <tr
                className={`${!substanceAbuseHistoryDataAgeOfFirstUseInhalants && !substanceAbuseHistoryDataLastUseInhalants && !substanceAbuseHistoryDataFrequencyInhalants && "table-row-hinde-print"}`}
              >
                <td>Inhalants</td>
                <td>
                  <Form.Control
                    as="textarea"
                    className={`ia-table-field ${!substanceAbuseHistoryDataAgeOfFirstUseInhalants && "hidePrint"}`}
                    type="text"
                    rows="1"
                    placeholder=""
                    value={substanceAbuseHistoryDataAgeOfFirstUseInhalants}
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUseInhalants(
                        e.target.value,
                      )
                    }
                  ></Form.Control>
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUseInhalants}
                    onChange={handlesubstanceAbuseHistoryDataLastUseInhalants}
                    options={optionsubstanceAbuseHistoryDataLastUseInhalants}
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLastUseInhalants
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyInhalants}
                    onChange={handlesubstanceAbuseHistoryDataFrequencyInhalants}
                    options={optionsubstanceAbuseHistoryDataFrequencyInhalants}
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataFrequencyInhalants
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLengthOfSobrietyInhalants}
                    onChange={
                      handlesubstanceAbuseHistoryDataLengthOfSobrietyInhalants
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLengthOfSobrietyInhalants
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyInhalants
                    }
                  />
                </td>
              </tr>
              <tr
                className={`${!substanceAbuseHistoryDataAgeOfFirstUseMarijuana && !substanceAbuseHistoryDataLastUseMarijuana && !substanceAbuseHistoryDataFrequencyMarijuana && "table-row-hinde-print"}`}
              >
                <td>Marijuana </td>
                <td>
                  <Form.Control
                    as="textarea"
                    className={`ia-table-field ${!substanceAbuseHistoryDataAgeOfFirstUseMarijuana && "table-row-hinde-print"}`}
                    type="text"
                    rows="1"
                    placeholder=""
                    value={substanceAbuseHistoryDataAgeOfFirstUseMarijuana}
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUseMarijuana(
                        e.target.value,
                      )
                    }
                  ></Form.Control>
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUseMarijuana}
                    onChange={handlesubstanceAbuseHistoryDataLastUseMarijuana}
                    options={optionsubstanceAbuseHistoryDataLastUseMarijuana}
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLastUseMarijuana
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyMarijuana}
                    onChange={handlesubstanceAbuseHistoryDataFrequencyMarijuana}
                    options={optionsubstanceAbuseHistoryDataFrequencyMarijuana}
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataFrequencyMarijuana
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLengthOfSobrietyMarijuana}
                    onChange={
                      handlesubstanceAbuseHistoryDataLengthOfSobrietyMarijuana
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLengthOfSobrietyMarijuana
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyMarijuana
                    }
                  />
                </td>
              </tr>
              <tr
                className={`${!substanceAbuseHistoryDataAgeOfFirstUseMethamphetamine && !substanceAbuseHistoryDataLastUseMethamphetamine && !substanceAbuseHistoryDataFrequencyMethamphetamine && "table-row-hinde-print"}`}
              >
                <td>Methamphetamine </td>
                <td>
                  <Form.Control
                    as="textarea"
                    className={`ia-table-field ${!substanceAbuseHistoryDataAgeOfFirstUseMethamphetamine && "hidePrint"}`}
                    type="text"
                    rows="1"
                    placeholder=""
                    value={
                      substanceAbuseHistoryDataAgeOfFirstUseMethamphetamine
                    }
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUseMethamphetamine(
                        e.target.value,
                      )
                    }
                  ></Form.Control>
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUseMethamphetamine}
                    onChange={
                      handlesubstanceAbuseHistoryDataLastUseMethamphetamine
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLastUseMethamphetamine
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLastUseMethamphetamine
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyMethamphetamine}
                    onChange={
                      handlesubstanceAbuseHistoryDataFrequencyMethamphetamine
                    }
                    options={
                      optionsubstanceAbuseHistoryDataFrequencyMethamphetamine
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataFrequencyMethamphetamine
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={
                      substanceAbuseHistoryDataLengthOfSobrietyMethamphetamine
                    }
                    onChange={
                      handlesubstanceAbuseHistoryDataLengthOfSobrietyMethamphetamine
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLengthOfSobrietyMethamphetamine
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyMethamphetamine
                    }
                  />
                </td>
              </tr>
              <tr
                className={`${!substanceAbuseHistoryDataAgeOfFirstUseMethadone && !substanceAbuseHistoryDataAgeOfFirstUseMethadone && !substanceAbuseHistoryDataLastUseMethadone && "table-row-hinde-print"}`}
              >
                <td>Methadone</td>
                <td>
                  <Form.Control
                    as="textarea"
                    className={`ia-table-field ${!substanceAbuseHistoryDataAgeOfFirstUseMethadone && "table-row-hinde-print"}`}
                    type="text"
                    rows="1"
                    placeholder=""
                    value={substanceAbuseHistoryDataAgeOfFirstUseMethadone}
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUseMethadone(
                        e.target.value,
                      )
                    }
                  ></Form.Control>
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUseMethadone}
                    onChange={handlesubstanceAbuseHistoryDataLastUseMethadone}
                    options={optionsubstanceAbuseHistoryDataLastUseMethadone}
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLastUseMethadone
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyMethadone}
                    onChange={handlesubstanceAbuseHistoryDataFrequencyMethadone}
                    options={optionsubstanceAbuseHistoryDataFrequencyMethadone}
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataFrequencyMethadone
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLengthOfSobrietyMethadone}
                    onChange={
                      hnadlesubstanceAbuseHistoryDataLengthOfSobrietyMethadone
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLengthOfSobrietyMethadone
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyMethadone
                    }
                  />
                </td>
              </tr>
              <tr
                className={`${!substanceAbuseHistoryDataAgeOfFirstUseMDMA && !substanceAbuseHistoryDataLastUseMDMA && !substanceAbuseHistoryDataFrequencyMDMA && "table-row-hinde-print"}`}
              >
                <td>MDMA (ecstasy)</td>
                <td>
                  <Form.Control
                    as="textarea"
                    className={`ia-table-field ${!substanceAbuseHistoryDataAgeOfFirstUseMDMA && "hidePrint"}`}
                    type="text"
                    rows="1"
                    placeholder=""
                    value={substanceAbuseHistoryDataAgeOfFirstUseMDMA}
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUseMDMA(
                        e.target.value,
                      )
                    }
                  ></Form.Control>
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUseMDMA}
                    onChange={handlesubstanceAbuseHistoryDataLastUseMDMA}
                    options={optionsubstanceAbuseHistoryDataLastUseMDMA}
                    isCreatable={true}
                    onKeyDown={handleKeysubstanceAbuseHistoryDataLastUseMDMA}
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyMDMA}
                    onChange={handlesubstanceAbuseHistoryDataFrequencyMDMA}
                    options={optionsubstanceAbuseHistoryDataFrequencyMDMA}
                    isCreatable={true}
                    onKeyDown={handleKeysubstanceAbuseHistoryDataFrequencyMDMA}
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLengthOfSobrietyMDMA}
                    onChange={
                      handlesubstanceAbuseHistoryDataLengthOfSobrietyMDMA
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLengthOfSobrietyMDMA
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyMDMA
                    }
                  />
                </td>
              </tr>
              <tr
                className={`${!substanceAbuseHistoryDataAgeOfFirstUsePCP && !substanceAbuseHistoryDataLastUsePCP && !substanceAbuseHistoryDataFrequencyPCP && "table-row-hinde-print"}`}
              >
                <td>Primary Care Physician (angel dust)</td>
                <td>
                  <Form.Control
                    as="textarea"
                    className={`ia-table-field ${!substanceAbuseHistoryDataAgeOfFirstUsePCP && "hidePrint"}`}
                    type="text"
                    rows="1"
                    placeholder=""
                    value={substanceAbuseHistoryDataAgeOfFirstUsePCP}
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUsePCP(
                        e.target.value,
                      )
                    }
                  ></Form.Control>
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUsePCP}
                    onChange={hnadlesubstanceAbuseHistoryDataLastUsePCP}
                    options={optionsubstanceAbuseHistoryDataLastUsePCP}
                    isCreatable={true}
                    onKeyDown={handleKeysubstanceAbuseHistoryDataLastUsePCP}
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyPCP}
                    onChange={handlesubstanceAbuseHistoryDataFrequencyPCP}
                    options={optionsubstanceAbuseHistoryDataFrequencyPCP}
                    isCreatable={true}
                    onKeyDown={handleKeysubstanceAbuseHistoryDataFrequencyPCP}
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLengthOfSobrietyPCP}
                    onChange={
                      handlesubstanceAbuseHistoryDataLengthOfSobrietyPCP
                    }
                    options={optionsubstanceAbuseHistoryDataLengthOfSobrietyPCP}
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyPCP
                    }
                  />
                </td>
              </tr>
              <tr
                className={`${!substanceAbuseHistoryDataAgeOfFirstUsePrescription && !substanceAbuseHistoryDataLastUsePrescription && !substanceAbuseHistoryDataFrequencyPrescription && "table-row-hinde-print"}`}
              >
                <td>Prescription medicine</td>
                <td>
                  <Form.Control
                    as="textarea"
                    className={`ia-table-field ${!substanceAbuseHistoryDataAgeOfFirstUsePrescription && "hidePrint"}`}
                    type="text"
                    rows="1"
                    placeholder=""
                    value={substanceAbuseHistoryDataAgeOfFirstUsePrescription}
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUsePrescription(
                        e.target.value,
                      )
                    }
                  ></Form.Control>
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUsePrescription}
                    onChange={
                      handlesubstanceAbuseHistoryDataLastUsePrescription
                    }
                    options={optionsubstanceAbuseHistoryDataLastUsePrescription}
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLastUsePrescription
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyPrescription}
                    onChange={
                      handlesubstanceAbuseHistoryDataFrequencyPrescription
                    }
                    options={
                      optionsubstanceAbuseHistoryDataFrequencyPrescription
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataFrequencyPrescription
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={
                      substanceAbuseHistoryDataLengthOfSobrietyPrescription
                    }
                    onChange={
                      hnadlesubstanceAbuseHistoryDataLengthOfSobrietyPrescription
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLengthOfSobrietyPrescription
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyPrescription
                    }
                  />
                </td>
              </tr>
              <tr
                className={`${!substanceAbuseHistoryDataAgeOfFirstUseOTC && !substanceAbuseHistoryDataLastUseOTC && !substanceAbuseHistoryDataFrequencyOTC && "table-row-hinde-print"}`}
              >
                <td>OTC medicine</td>
                <td>
                  <Form.Control
                    as="textarea"
                    className={`ia-table-field ${!substanceAbuseHistoryDataAgeOfFirstUseOTC && "table-row-hinde-print"}`}
                    type="text"
                    rows="1"
                    placeholder=""
                    value={substanceAbuseHistoryDataAgeOfFirstUseOTC}
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUseOTC(
                        e.target.value,
                      )
                    }
                  ></Form.Control>
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUseOTC}
                    onChange={hnadlesubstanceAbuseHistoryDataLastUseOTC}
                    options={optionsubstanceAbuseHistoryDataLastUseOTC}
                    isCreatable={true}
                    onKeyDown={handleKeysubstanceAbuseHistoryDataLastUseOTC}
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyOTC}
                    onChange={handlesubstanceAbuseHistoryDataFrequencyOTC}
                    options={optionsubstanceAbuseHistoryDataFrequencyOTC}
                    isCreatable={true}
                    onKeyDown={handleKeysubstanceAbuseHistoryDataFrequencyOTC}
                    className="z-1"
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLengthOfSobrietyOTC}
                    onChange={
                      handlesubstanceAbuseHistoryDataLengthOfSobrietyOTC
                    }
                    options={optionsubstanceAbuseHistoryDataLengthOfSobrietyOTC}
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyOTC
                    }
                  />
                </td>
              </tr>

              <tr
                className={`${!substanceAbuseHistoryDataAgeOfFirstUseCocaine && "table-row-hide-print"}`}
              >
                <td>Cocaine</td>
                <td>
                  <Form.Control
                    size="sm"
                    type="text"
                    placeholder=""
                    value={substanceAbuseHistoryDataAgeOfFirstUseCocaine}
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUseCocaine(
                        e.target.value,
                      )
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUseCocaine}
                    onChange={hnadlesubstanceAbuseHistoryDataLastUseCocaine}
                    options={optionsubstanceAbuseHistoryDataLastUseCocaine}
                    isCreatable={true}
                    onKeyDown={handleKeysubstanceAbuseHistoryDataLastUseCocaine}
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyCocaine}
                    onChange={handlesubstanceAbuseHistoryDataFrequencyCocaine}
                    options={optionsubstanceAbuseHistoryDataFrequencyCocaine}
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataFrequencyCocaine
                    }
                    className="z-1"
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLengthOfSobrietyCocaine}
                    onChange={
                      handlesubstanceAbuseHistoryDataLengthOfSobrietyCocaine
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLengthOfSobrietyCocaine
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyCocaine
                    }
                  />
                </td>
              </tr>

              <tr
                className={`${!substanceAbuseHistoryDataAgeOfFirstUseHallucinogens && "table-row-hide-print"}`}
              >
                <td>Hallucinogens (LSD,mescaline,etc.)</td>
                <td>
                  <Form.Control
                    size="sm"
                    type="text"
                    placeholder=""
                    value={substanceAbuseHistoryDataAgeOfFirstUseHallucinogens}
                    onChange={(e) =>
                      setSubstanceAbuseHistoryDataAgeOfFirstUseHallucinogens(
                        e.target.value,
                      )
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataLastUseHallucinogens}
                    onChange={
                      hnadlesubstanceAbuseHistoryDataLastUseHallucinogens
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLastUseHallucinogens
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLastUseHallucinogens
                    }
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={substanceAbuseHistoryDataFrequencyHallucinogens}
                    onChange={
                      handlesubstanceAbuseHistoryDataFrequencyHallucinogens
                    }
                    options={
                      optionsubstanceAbuseHistoryDataFrequencyHallucinogens
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataFrequencyHallucinogens
                    }
                    className="z-1"
                  />
                </td>
                <td>
                  <SelectSinglePrint
                    value={
                      substanceAbuseHistoryDataLengthOfSobrietyHallucinogens
                    }
                    onChange={
                      handlesubstanceAbuseHistoryDataLengthOfSobrietyHallucinogens
                    }
                    options={
                      optionsubstanceAbuseHistoryDataLengthOfSobrietyHallucinogens
                    }
                    isCreatable={true}
                    onKeyDown={
                      handleKeysubstanceAbuseHistoryDataLengthOfSobrietyHallucinogens
                    }
                  />
                </td>
              </tr>

              {typeArray?.map((i, index) => {
                return (
                  <tr
                    key={index}
                    className={`${!i.types && "table-row-hinde-print"}`}
                  >
                    <td>{i.types}</td>
                    <td>{i.ageOfFirstUse} </td>
                    <td>{i.lastUse} </td>
                    <td>{i.frequency} </td>
                    <td
                      className={`${canDelete && i.lengthOfSobriety && "flex justify-between"}`}
                    >
                      <p>{i.lengthOfSobriety}</p>
                      {canDelete && (
                        <div className="icon-joiner hidePrint">
                          <span
                            className="del-btn cursor-pointer"
                            onClick={() => removeTypeArray(index)}
                          >
                            <AiFillDelete />
                          </span>
                        </div>
                      )}
                    </td>
                  </tr>
                );
              })}

              <tr
                className={`${!otherTypeOther && !otherAgeOfFirstUse && !otherLastUse && "table-row-hinde-print"}`}
              >
                <td className={`${!otherTypeOther && "table-row-hinde-print"}`}>
                  Other:
                  <input
                    type="text"
                    placeholder="___________"
                    value={otherTypeOther}
                    onChange={(e) => setOtherTypeOther(e.target.value)}
                  />
                </td>
                <td>
                  <Form.Control
                    as="textarea"
                    className={`ia-table-field ${!otherAgeOfFirstUse && "table-row-hinde-print"}`}
                    type="text"
                    rows="1"
                    placeholder=""
                    value={otherAgeOfFirstUse}
                    onChange={(e) => setOtherAgeOfFirstUse(e.target.value)}
                  ></Form.Control>
                </td>
                <td className={`${!otherLastUse && "table-row-hinde-print"}`}>
                  <SelectSinglePrint
                    value={otherLastUse}
                    onChange={handleotherLastUse}
                    options={optionotherLastUse}
                    isCreatable={true}
                    onKeyDown={handleKeyotherLastUse}
                  />
                </td>
                <td className={`${!otherFrequancy && "table-row-hinde-print"}`}>
                  <SelectSinglePrint
                    value={otherFrequancy}
                    onChange={handleotherFrequancy}
                    options={optionotherFrequancy}
                    isCreatable={true}
                    onKeyDown={handleKeyotherFrequancy}
                  />
                </td>
                <td
                  className={`${!OtherlengthOfSobrifty && "table-row-hinde-print"}`}
                >
                  <SelectSinglePrint
                    value={OtherlengthOfSobrifty}
                    onChange={handleOtherlengthOfSobrifty}
                    options={optionOtherlengthOfSobrifty}
                    isCreatable={true}
                    onKeyDown={handleKeyOtherlengthOfSobrifty}
                  />
                </td>
              </tr>
            </tbody>
          </Table>
        </Col>
      </Row>
      <Row className="mb-3 table-row-hinde-print">
        <Col xs={12} className="text-center">
          <Button
            type="button"
            className="theme-button"
            onClick={handleTypeOfArray}
          >
            Add
          </Button>
        </Col>
      </Row>
    </>
  );
}

export const SUBSTANCE_ABUSE_SECTION_PROP_KEYS = [
  "OtherlengthOfSobrifty",
  "canDelete",
  "handleKeyOtherlengthOfSobrifty",
  "handleKeyotherFrequancy",
  "handleKeyotherLastUse",
  "handleKeysubstanceAbuseHistoryDataFrequencyAlcohol",
  "handleKeysubstanceAbuseHistoryDataFrequencyBenzodiazepines",
  "handleKeysubstanceAbuseHistoryDataFrequencyCocaine",
  "handleKeysubstanceAbuseHistoryDataFrequencyCrack",
  "handleKeysubstanceAbuseHistoryDataFrequencyHallucinogens",
  "handleKeysubstanceAbuseHistoryDataFrequencyHeroin",
  "handleKeysubstanceAbuseHistoryDataFrequencyInhalants",
  "handleKeysubstanceAbuseHistoryDataFrequencyMDMA",
  "handleKeysubstanceAbuseHistoryDataFrequencyMarijuana",
  "handleKeysubstanceAbuseHistoryDataFrequencyMethadone",
  "handleKeysubstanceAbuseHistoryDataFrequencyMethamphetamine",
  "handleKeysubstanceAbuseHistoryDataFrequencyOTC",
  "handleKeysubstanceAbuseHistoryDataFrequencyPCP",
  "handleKeysubstanceAbuseHistoryDataFrequencyPrescription",
  "handleKeysubstanceAbuseHistoryDataLastUseAlcohol",
  "handleKeysubstanceAbuseHistoryDataLastUseBenzodiazepines",
  "handleKeysubstanceAbuseHistoryDataLastUseCocaine",
  "handleKeysubstanceAbuseHistoryDataLastUseCrack",
  "handleKeysubstanceAbuseHistoryDataLastUseHallucinogens",
  "handleKeysubstanceAbuseHistoryDataLastUseHeroin",
  "handleKeysubstanceAbuseHistoryDataLastUseInhalants",
  "handleKeysubstanceAbuseHistoryDataLastUseMDMA",
  "handleKeysubstanceAbuseHistoryDataLastUseMarijuana",
  "handleKeysubstanceAbuseHistoryDataLastUseMethadone",
  "handleKeysubstanceAbuseHistoryDataLastUseMethamphetamine",
  "handleKeysubstanceAbuseHistoryDataLastUseOTC",
  "handleKeysubstanceAbuseHistoryDataLastUsePCP",
  "handleKeysubstanceAbuseHistoryDataLastUsePrescription",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyAlcohol",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyCocaine",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyCrack",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyHallucinogens",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyHeroin",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyInhalants",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyMDMA",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyMarijuana",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyMethadone",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyMethamphetamine",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyOTC",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyPCP",
  "handleKeysubstanceAbuseHistoryDataLengthOfSobrietyPrescription",
  "handleOtherlengthOfSobrifty",
  "handleTypeOfArray",
  "handleotherFrequancy",
  "handleotherLastUse",
  "handlersubstanceAbuseHistoryDataFrequencyAlcohol",
  "handlersubstanceAbuseHistoryDataLastUseAlcohol",
  "handlersubstanceAbuseHistoryDataLengthOfSobrietyAlcohol",
  "handlesubstanceAbuseHistoryDataFrequencyBenzodiazepines",
  "handlesubstanceAbuseHistoryDataFrequencyCocaine",
  "handlesubstanceAbuseHistoryDataFrequencyCrack",
  "handlesubstanceAbuseHistoryDataFrequencyHallucinogens",
  "handlesubstanceAbuseHistoryDataFrequencyHeroin",
  "handlesubstanceAbuseHistoryDataFrequencyInhalants",
  "handlesubstanceAbuseHistoryDataFrequencyMDMA",
  "handlesubstanceAbuseHistoryDataFrequencyMarijuana",
  "handlesubstanceAbuseHistoryDataFrequencyMethadone",
  "handlesubstanceAbuseHistoryDataFrequencyMethamphetamine",
  "handlesubstanceAbuseHistoryDataFrequencyOTC",
  "handlesubstanceAbuseHistoryDataFrequencyPCP",
  "handlesubstanceAbuseHistoryDataFrequencyPrescription",
  "handlesubstanceAbuseHistoryDataLastUseBenzodiazepines",
  "handlesubstanceAbuseHistoryDataLastUseCrack",
  "handlesubstanceAbuseHistoryDataLastUseHeroin",
  "handlesubstanceAbuseHistoryDataLastUseInhalants",
  "handlesubstanceAbuseHistoryDataLastUseMDMA",
  "handlesubstanceAbuseHistoryDataLastUseMarijuana",
  "handlesubstanceAbuseHistoryDataLastUseMethadone",
  "handlesubstanceAbuseHistoryDataLastUseMethamphetamine",
  "handlesubstanceAbuseHistoryDataLastUsePrescription",
  "handlesubstanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines",
  "handlesubstanceAbuseHistoryDataLengthOfSobrietyCocaine",
  "handlesubstanceAbuseHistoryDataLengthOfSobrietyCrack",
  "handlesubstanceAbuseHistoryDataLengthOfSobrietyHallucinogens",
  "handlesubstanceAbuseHistoryDataLengthOfSobrietyHeroin",
  "handlesubstanceAbuseHistoryDataLengthOfSobrietyInhalants",
  "handlesubstanceAbuseHistoryDataLengthOfSobrietyMDMA",
  "handlesubstanceAbuseHistoryDataLengthOfSobrietyMarijuana",
  "handlesubstanceAbuseHistoryDataLengthOfSobrietyMethamphetamine",
  "handlesubstanceAbuseHistoryDataLengthOfSobrietyOTC",
  "handlesubstanceAbuseHistoryDataLengthOfSobrietyPCP",
  "hnadlesubstanceAbuseHistoryDataLastUseCocaine",
  "hnadlesubstanceAbuseHistoryDataLastUseHallucinogens",
  "hnadlesubstanceAbuseHistoryDataLastUseOTC",
  "hnadlesubstanceAbuseHistoryDataLastUsePCP",
  "hnadlesubstanceAbuseHistoryDataLengthOfSobrietyMethadone",
  "hnadlesubstanceAbuseHistoryDataLengthOfSobrietyPrescription",
  "id",
  "optionOtherlengthOfSobrifty",
  "optionotherFrequancy",
  "optionotherLastUse",
  "optionsubstanceAbuseHistoryDataFrequencyBenzodiazepines",
  "optionsubstanceAbuseHistoryDataFrequencyCocaine",
  "optionsubstanceAbuseHistoryDataFrequencyCrack",
  "optionsubstanceAbuseHistoryDataFrequencyHallucinogens",
  "optionsubstanceAbuseHistoryDataFrequencyHeroin",
  "optionsubstanceAbuseHistoryDataFrequencyInhalants",
  "optionsubstanceAbuseHistoryDataFrequencyMDMA",
  "optionsubstanceAbuseHistoryDataFrequencyMarijuana",
  "optionsubstanceAbuseHistoryDataFrequencyMethadone",
  "optionsubstanceAbuseHistoryDataFrequencyMethamphetamine",
  "optionsubstanceAbuseHistoryDataFrequencyOTC",
  "optionsubstanceAbuseHistoryDataFrequencyPCP",
  "optionsubstanceAbuseHistoryDataFrequencyPrescription",
  "optionsubstanceAbuseHistoryDataLastUseBenzodiazepines",
  "optionsubstanceAbuseHistoryDataLastUseCocaine",
  "optionsubstanceAbuseHistoryDataLastUseCrack",
  "optionsubstanceAbuseHistoryDataLastUseHallucinogens",
  "optionsubstanceAbuseHistoryDataLastUseHeroin",
  "optionsubstanceAbuseHistoryDataLastUseInhalants",
  "optionsubstanceAbuseHistoryDataLastUseMDMA",
  "optionsubstanceAbuseHistoryDataLastUseMarijuana",
  "optionsubstanceAbuseHistoryDataLastUseMethadone",
  "optionsubstanceAbuseHistoryDataLastUseMethamphetamine",
  "optionsubstanceAbuseHistoryDataLastUseOTC",
  "optionsubstanceAbuseHistoryDataLastUsePCP",
  "optionsubstanceAbuseHistoryDataLastUsePrescription",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyAlcohol",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyCocaine",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyCrack",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyHallucinogens",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyHeroin",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyInhalants",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyMDMA",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyMarijuana",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyMethadone",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyMethamphetamine",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyOTC",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyPCP",
  "optionsubstanceAbuseHistoryDataLengthOfSobrietyPrescription",
  "otherAgeOfFirstUse",
  "otherFrequancy",
  "otherLastUse",
  "otherTypeOther",
  "removeTypeArray",
  "selectedsubstanceAbuseHistoryDataFrequencyAlcohol",
  "selectedsubstanceAbuseHistoryDataLastUseAlcohol",
  "setOtherAgeOfFirstUse",
  "setOtherTypeOther",
  "setSubstanceAbuseDenies",
  "setSubstanceAbuseHistory",
  "setSubstanceAbuseHistoryDataAgeOfFirstUseAlcohol",
  "setSubstanceAbuseHistoryDataAgeOfFirstUseBenzodiazepines",
  "setSubstanceAbuseHistoryDataAgeOfFirstUseCocaine",
  "setSubstanceAbuseHistoryDataAgeOfFirstUseCrack",
  "setSubstanceAbuseHistoryDataAgeOfFirstUseHallucinogens",
  "setSubstanceAbuseHistoryDataAgeOfFirstUseHeroin",
  "setSubstanceAbuseHistoryDataAgeOfFirstUseInhalants",
  "setSubstanceAbuseHistoryDataAgeOfFirstUseMDMA",
  "setSubstanceAbuseHistoryDataAgeOfFirstUseMarijuana",
  "setSubstanceAbuseHistoryDataAgeOfFirstUseMethadone",
  "setSubstanceAbuseHistoryDataAgeOfFirstUseMethamphetamine",
  "setSubstanceAbuseHistoryDataAgeOfFirstUseOTC",
  "setSubstanceAbuseHistoryDataAgeOfFirstUsePCP",
  "setSubstanceAbuseHistoryDataAgeOfFirstUsePrescription",
  "substanceAbuseDenies",
  "substanceAbuseHistory",
  "substanceAbuseHistoryDataAgeOfFirstUseAlcohol",
  "substanceAbuseHistoryDataAgeOfFirstUseBenzodiazepines",
  "substanceAbuseHistoryDataAgeOfFirstUseCocaine",
  "substanceAbuseHistoryDataAgeOfFirstUseCrack",
  "substanceAbuseHistoryDataAgeOfFirstUseHallucinogens",
  "substanceAbuseHistoryDataAgeOfFirstUseHeroin",
  "substanceAbuseHistoryDataAgeOfFirstUseInhalants",
  "substanceAbuseHistoryDataAgeOfFirstUseMDMA",
  "substanceAbuseHistoryDataAgeOfFirstUseMarijuana",
  "substanceAbuseHistoryDataAgeOfFirstUseMethadone",
  "substanceAbuseHistoryDataAgeOfFirstUseMethamphetamine",
  "substanceAbuseHistoryDataAgeOfFirstUseOTC",
  "substanceAbuseHistoryDataAgeOfFirstUsePCP",
  "substanceAbuseHistoryDataAgeOfFirstUsePrescription",
  "substanceAbuseHistoryDataFrequencyAlcohol",
  "substanceAbuseHistoryDataFrequencyBenzodiazepines",
  "substanceAbuseHistoryDataFrequencyCocaine",
  "substanceAbuseHistoryDataFrequencyCrack",
  "substanceAbuseHistoryDataFrequencyHallucinogens",
  "substanceAbuseHistoryDataFrequencyHeroin",
  "substanceAbuseHistoryDataFrequencyInhalants",
  "substanceAbuseHistoryDataFrequencyMDMA",
  "substanceAbuseHistoryDataFrequencyMarijuana",
  "substanceAbuseHistoryDataFrequencyMethadone",
  "substanceAbuseHistoryDataFrequencyMethamphetamine",
  "substanceAbuseHistoryDataFrequencyOTC",
  "substanceAbuseHistoryDataFrequencyPCP",
  "substanceAbuseHistoryDataFrequencyPrescription",
  "substanceAbuseHistoryDataLastUseAlcohol",
  "substanceAbuseHistoryDataLastUseBenzodiazepines",
  "substanceAbuseHistoryDataLastUseCocaine",
  "substanceAbuseHistoryDataLastUseCrack",
  "substanceAbuseHistoryDataLastUseHallucinogens",
  "substanceAbuseHistoryDataLastUseHeroin",
  "substanceAbuseHistoryDataLastUseInhalants",
  "substanceAbuseHistoryDataLastUseMDMA",
  "substanceAbuseHistoryDataLastUseMarijuana",
  "substanceAbuseHistoryDataLastUseMethadone",
  "substanceAbuseHistoryDataLastUseMethamphetamine",
  "substanceAbuseHistoryDataLastUseOTC",
  "substanceAbuseHistoryDataLastUsePCP",
  "substanceAbuseHistoryDataLastUsePrescription",
  "substanceAbuseHistoryDataLengthOfSobrietyAlcohol",
  "substanceAbuseHistoryDataLengthOfSobrietyBenzodiazepines",
  "substanceAbuseHistoryDataLengthOfSobrietyCocaine",
  "substanceAbuseHistoryDataLengthOfSobrietyCrack",
  "substanceAbuseHistoryDataLengthOfSobrietyHallucinogens",
  "substanceAbuseHistoryDataLengthOfSobrietyHeroin",
  "substanceAbuseHistoryDataLengthOfSobrietyInhalants",
  "substanceAbuseHistoryDataLengthOfSobrietyMDMA",
  "substanceAbuseHistoryDataLengthOfSobrietyMarijuana",
  "substanceAbuseHistoryDataLengthOfSobrietyMethadone",
  "substanceAbuseHistoryDataLengthOfSobrietyMethamphetamine",
  "substanceAbuseHistoryDataLengthOfSobrietyOTC",
  "substanceAbuseHistoryDataLengthOfSobrietyPCP",
  "substanceAbuseHistoryDataLengthOfSobrietyPrescription",
  "typeArray",
];
