name: EKS Cluster Deployment Backend CI/CD k8s
run-name: ${{ github.ref_name }} - EKS Cluster Deployment k8s
on: 
  push:
    branches:
      - main
  workflow_dispatch:    
concurrency:
  group: employee-cicd-k8s  
jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGE_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGE_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_STAGE_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_STAGE_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"



  continuous-deployment:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: continuous-integration

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGE_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGE_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_STAGE_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Setup Helm
        uses: Azure/setup-helm@v3.5
        with:
          version: 'v3.16.1'
  
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4.0.0
          
  
      - name: Get EKS Kubeconfig
        run: |
          aws eks --region ${{ secrets.AWS_STAGE_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}  
      - name: Deploy Helm chart
        run: helm upgrade --install oasis-employee-website -n prod --create-namespace --atomic --timeout 7m  --set image.repository=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_STAGE_REPOSITORY_NAME }}  --set image.tag=${{ github.sha }} ./helm-chart-prod
